web:
 image: wordpress
 environment:
  - WORDPRESS_DB_HOST=localhost
  - WORDPRESS_DB_USER=root
  - WORDPRESS_DB_PASSWORD=password
 links:
  - db

db:
 image: mysql
 environment:
  - MYSQL_ROOT_PASSWORD=password